### ISSUE TITLE
Possibility to choose the upload method when taking a screenshot

### ISSUE THREAD

**Issue by EVOTk** [clowd/Clowd#19]
Do you think it would be possible to choose the upload method when taking a screenshot?
For example via a long press on "Upload" if several methods are specified.

 Thanks 😃

**Comment by caesay** [comment]
You can now right-click the "Upload" button in the image editor to choose from a list of enabled image providers. Available in 3.4.451

**Comment by EVOTk** [comment]
Works very well for me! Thank you very much for this new feature

![image](https://user-images.githubusercontent.com/45015615/194780323-08bd07df-773c-40b1-8403-e238c9beaf8a.png)
