### ISSUE TITLE
Clicking outside a text box doesn't exit edit mode anymore

### ISSUE THREAD

**Issue by rstarkov** [clowd/Clowd#20]
Enter the textbox edit mode. Click outside the textbox. Expected: the text gets committed. Actual: what I clicked gets selected, but I'm still editing the textbox and it's still receiving keyboard input.

Version 3.4.442+b786f0

**Comment by EVOTk** [comment]
Indeed I have the same behavior, I right click to "validate" when editing

**Comment by caesay** [comment]
I believe this is fixed in 6a3007f7416891e31cdca708c0b0e96a807134b5 (3.4.446)
