### ISSUE TITLE
Minimized at system startup

### ISSUE THREAD

**Issue by TechInfoFr** [clowd/Clowd#22]
Hello,

Would it be possible to get clowd minimized on Windows startup?

Thanks for this software.

**Comment by caesay** [comment]
Hi, Clowd is minimized to the system tray when it starts, can you clarify what you are asking for?

**Comment by TechInfoFr** [comment]
Hi,

this software has its window open every time Windows starts, on 2 computers
with Windows 10 and is not minimized to the system tray.



Le dim. 9 oct. 2022, 12:26, Caelan Sayler ***@***.***> a
écrit :

**Comment by caesay** [comment]
I do not know what you mean.

Are you referring to this settings window?

![image](https://user-images.githubusercontent.com/1287295/194777471-0b21e9b8-ecd6-4d70-9057-a8d2b0f8bb07.png)

This window only appears when the app is first installed, and after it's updated.

If you are referring to an image editor window, those are saved and will re-open if clowd is closed or your computer is restarted. You can turn this off with the setting: `Editor > Restore sessions on Clowd start`

![image](https://user-images.githubusercontent.com/1287295/194777508-e231a94c-4a84-4db0-978c-f98d50165f0e.png)

**Comment by TechInfoFr** [comment]
Hi,

I have this window every time the computer starts, even if it was closed at
the time of shutdown.
[image: image.png]
And this on 2 PCs with Windows 10.

I'm sorry :-/


Bien cordialement.

--Signature--
Si vous jugez que l'email reçu est important, merci de m'en valider la
bonne réception ! (Juste un "Bien reçu" suffit)

*Mickaël BELLARD*
***@***.***
  *N'imprimez ce mail que si nécessaire, pensez à l'environnement.*


Le dim. 9 oct. 2022 à 22:12, Caelan Sayler ***@***.***> a
écrit :

**Comment by caesay** [comment]
It looks like you tried to attach an image via email, but that didn't come through on GitHub. Any chance you could re-upload that image on the GitHub issue online? I'd really like to look into this for you!

**Comment by TechInfoFr** [comment]
It's juste the main windows of the soft with the version number (General,
check for update button...)

v3.4.445+8a3e8e


Bien cordialement.

--Signature--
Si vous jugez que l'email reçu est important, merci de m'en valider la
bonne réception ! (Juste un "Bien reçu" suffit)

*Mickaël BELLARD*
***@***.***
  *N'imprimez ce mail que si nécessaire, pensez à l'environnement.*


Le lun. 10 oct. 2022 à 11:36, Caelan Sayler ***@***.***> a
écrit :

**Comment by TechInfoFr** [comment]
Sorry for the inconvenience, the general window is no longer present at
startup now ... 😬

--Signature--
Si vous jugez que l'email reçu est important, merci de m'en valider la
bonne réception ! (Juste un "Bien reçu" suffit)

Mickaël Bellard

Le mer. 26 oct. 2022, 11:59, Caelan Sayler ***@***.***> a
écrit :
