### ISSUE TITLE
Remove the countdown at begining of a recording ? 

### ISSUE THREAD

**Issue by Felzow47** [clowd/Clowd#23]

**Comment by caesay** [comment]
Hi, can you let me know what is the use-case for this feature? Are you looking to start the recording faster without having to wait? or are you looking to have the recording start at a precise time?

During the count-down is when Clowd is allocating memory resources and preparing to record. That preparation usually takes a few seconds, so simply removing the count-down may not achieve what you want. Depending on your PC it still might take a couple of seconds after pushing the button before the recording starts.

**Comment by Felzow47** [comment]
hello ! yes it's just because I don't want to wait XD but if there is a question of optimization I could do with your software already and so much more practical than starting obs and configuring to record...
