### ISSUE TITLE
Function to pre-select areas to keep hidden/obscure while taking a video

### ISSUE THREAD

**Issue by EVOTk** [clowd/Clowd#26]
Hello 

Do you think it would be possible to add a function to pre-select areas to keep hidden/obscure while taking a video?

Thx

**Comment by EVOTk** [comment]
Hello,
The goal would be to be able to make a video that takes up a large part of the screen without having to reveal the whole thing (like the central part).

for example here for an example of navigation in this application, there is no need for the central part with the personal photos displayed, it could very well be kept obscured/hidden while taking the video.


Edit : I take advantage of this, also, do you think it would be possible to have options on the Obscure function in order to increase the blur?

**Comment by caesay** [comment]
In the case of video, is it ok if this effect is also visible to you on screen? or are you looking for the obscure to only appear on the video and not on the screen you see? Is the current "Draw on Screen" capabilities sufficient for this? It already has the ability to draw shapes on your screen that will appear on video. There is no obscure option but you could draw a black rectangle.

**Comment by caesay** [comment]
![image](https://user-images.githubusercontent.com/1287295/202908535-0ef4ca2e-c960-4226-8e61-8db8a0cf3594.png)
It is now possible to edit the blur radius via the Pixelate tool.

**Comment by EVOTk** [comment]
Thank you very much for this :)

**Comment by caesay** [comment]
I have also added a filled rectangle to the screen drawing tools 
![image](https://user-images.githubusercontent.com/1287295/202915220-c08c969c-2b5c-4614-8b78-591d28212516.png)

**Comment by EVOTk** [comment]
Perfect , big thx !
