### ISSUE TITLE
Black screen on video recording 

### ISSUE THREAD

**Issue by loginfordash** [clowd/Clowd#33]
i tried everything change format + quality but still outputs came black.

https://i.imgur.com/uJp7kCJ.png

**Comment by loginfordash** [comment]
https://i.imgur.com/SRJ8GSs.png

**Comment by caesay** [comment]
Are you trying to record anything in particular? Keep in mind that anything DRM protected (eg. Netflix) will appear black in recordings. If that is not your issue, can you try performing a recording, and then going to `%localappdata%\Clowd\Clowd.log` and sending me the recording log? If you are not comfortable sharing the log publicly on GitHub you can email it to git@caesay.com.

**Comment by caesay** [comment]
As there has not been any additional details (eg. logs) I am going to close this for now.
