### ISSUE TITLE
The creation of a gif also create a mp4

### ISSUE THREAD

**Issue by EVOTk** [clowd/Clowd#34]
Hello,

When I use the video recording function, I select GIF. 
Then I save it in a folder.
So I find in this folder with my GIF, but also the video in MP4

Clowd 3.4.484

![image](https://user-images.githubusercontent.com/45015615/205303738-cdbe495a-9f53-4164-8d7b-17ca0a1d49cb.png)

**Comment by caesay** [comment]
Yes, that is working as intended. The video is encoded as an MP4 while you are recording your screen because the compression is higher. Once your recording is done, it is re-encoded as a gif.

**Comment by EVOTk** [comment]
Ho ! okay :D
