### ISSUE TITLE
Why "obligatory" recent history?

### ISSUE THREAD

**Issue by Shituation** [clowd/Clowd#35]
Why cannot we disable the history of made screenshots?

**Comment by caesay** [comment]
Clowd only shows screenshots you open in an editor in the Recent tab. If you copy to clipboard directly from the PrntScr window, it will not appear in the Recent tab.

Clowd can not operate the screenshot editor without persisting your screenshot, editing history, and other graphical objects to your hard drive. These sessions being saved also allow other features, like automatically re-opening open clowd sessions when you reboot.

You are able to configure how long Clowd keeps these sessions stored via the "Editor" tab in settings. The default is for 30 days. You could set this to one hour if you wish.

I could allow you to remove the "Recent" tab from the settings UI, but it would not remove those required files from being stored on your disk, and I don't believe that removing that page would be helpful.
