### ISSUE TITLE
jpg instead of png as default format for save.

### ISSUE THREAD

**Issue by Shituation** [clowd/Clowd#41]
Make jpg instead of png as default format for save. Png for screenshots by default is only increasing size of the screenshot for no real gains. If people needs lossless screenshots they can switch to png manually.

**Comment by caesay** [comment]
It is possible to do this in the by adding `.jpg` to the end of the Filename pattern in capture settings. Example:
![image](https://user-images.githubusercontent.com/1287295/233373692-d39f36ae-cf9f-47ee-a25f-976e03613e16.png)
