### ISSUE TITLE
Error during video recording with sound

### ISSUE THREAD

**Issue by BunnySweety** [clowd/Clowd#6]
When starting to record a video with sound, this error occurs :

![screenshot](https://user-images.githubusercontent.com/111603921/189335541-f7f8740a-2586-454e-a307-afc9a9ff30e3.png)

We find the same message in the log generated in the destination folder. It does not happen when the sound is not activated in the recording settings.

Clowd version : 3.4.371+645041
OS : Windows 10 21H2

**Comment by caesay** [comment]
Thanks a lot for reporting this! I believe I have fixed the issue in v3.4.396. This is available as an experimental release which you can get by going to "General" settings and turning on experimental updates. Would you be able to update and check if the issue is resolved for you?

**Comment by BunnySweety** [comment]
I followed the instructions and it works with the experimental version 3.4.396+23020a

Thanks for your help
