### ISSUE TITLE
Restore the Maximised state of editor windows on restart

### ISSUE THREAD

**Issue by rstarkov** [clowd/Clowd#8]
When Clowd restarts it reopens all editor windows in their original positions, but does not restore the maximised state. It should.

**Comment by caesay** [comment]
To add to this, I find that sometimes windows are restored to totally bonkers coordinates (like `-32000,-32000`). The restore algorithm should endeavour to find a place where the window can be restored on an existing monitor (even if the original monitor no longer exists). It's restored bounds should never have any area off screen.

**Comment by rstarkov** [comment]
![image](https://user-images.githubusercontent.com/149002/199974002-2a037c70-9260-40e1-9c57-26000723baa4.png)

I imagine this is the same issue as restoring to bonkers coordinates. Happens reasonably often. This is what they look like in Alt+Tab, and nothing visibly changes when they are activated (but can be fixed with Alt+Space)

**Comment by caesay** [comment]
Yes this is the same behavior I see when the window is restored off screen
